name: Build and Package Desktop Apps

on:
  push:
    branches:
      - main # 你可以根据需要修改为你的主分支名称
  release:
    types: [released]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    name: (${{ matrix.os }})

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
        with:
          lfs: true

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.3
        with:
          node-version: 16.17 # 使用 LTS 版本

      - name: Enable Corepack and Yarn
        run: corepack enable yarn

      - name: Restore cache
        uses: actions/cache@v4.0.0
        with:
          path: |
            .yarn/cache
            **/node_modules
          key: v5-${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: v5-${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build and Package for OS
        run: |
          yarn run desktop:build:prod
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            yarn run package:win
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            yarn run package:darwin
          elif [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            yarn run package:linux
          fi
      - name: Upload artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: packaged-app
          path: |
            dist/**/*.exe
            dist/**/*.deb
            dist/**/*.dmg
